### ISSUE TITLE
diaspora docker

### ISSUE THREAD

**Issue by Docjones** [Angristan/dockerfiles#3]
Hello,

using your docker-compose-file for diaspora, i receive the following error when starting the migration commmand:
```
PS D:\srv\diaspora> docker-compose run --rm unicorn bin/rake db:create db:migrate
Creating diaspora_postgres ... done
Creating diaspora_redis    ... done
/usr/local/lib/ruby/2.4.0/psych.rb:472:in `initialize': Is a directory @ io_fillbuf - fd:9 /diaspora/config/diaspora.yml (Errno::EISDIR)
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `open'
        from /usr/local/lib/ruby/2.4.0/psych.rb:472:in `load_file'
        from /diaspora/vendor/bundle/ruby/2.4.0/gems/configurate-0.3.1/lib/configurate/provider/yaml.rb:20:in `initialize'
        from /diaspora/vendor/bundle/ruby/2.4.0/gems/configurate-0.3.1/lib/configurate/lookup_chain.rb:21:in `new'
        from /diaspora/vendor/bundle/ruby/2.4.0/gems/configurate-0.3.1/lib/configurate/lookup_chain.rb:21:in `add_provider'
        from /diaspora/config/load_config.rb:29:in `block in <top (required)>'
        from /diaspora/vendor/bundle/ruby/2.4.0/gems/configurate-0.3.1/lib/configurate.rb:69:in `instance_eval'
        from /diaspora/vendor/bundle/ruby/2.4.0/gems/configurate-0.3.1/lib/configurate.rb:69:in `create'
        from /diaspora/config/load_config.rb:19:in `<top (required)>'
        from /diaspora/config/boot.rb:8:in `require_relative'
        from /diaspora/config/boot.rb:8:in `<top (required)>'
        from bin/rake:7:in `require_relative'
        from bin/rake:7:in `<main>'
```
I am using your docker-compose.yml file and adapted the diaspora.yml and database.yml. Do you have any idea?

thanks & regards
/D

**Comment by angristan** [comment]
Hello,

In your directory, can you do a `ls -l` and show me your docker-compose.yml?

**Comment by Docjones** [comment]
Hello,

here is my docker-compose.yml (same as from the repo):
```
version: '2.3'

services:
  postgres:
    container_name: diaspora_postgres
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=diaspora
      - POSTGRES_PASSWORD=diaspora
      - POSTGRES_DB=diaspora_production

  redis:
    container_name: diaspora_redis
    image: redis:4.0-alpine
    restart: always
    volumes:
      - ./redis:/data

  unicorn:
    container_name: diaspora_unicorn
    image: angristan/diaspora:0.7.5.0
    restart: always
    command: bin/bundle exec unicorn -c config/unicorn.rb -E production
    volumes:
      - ./data:/diaspora/public/
      - ./diaspora.yml:/diaspora/config/diaspora.yml
      - ./database.yml:/diaspora/config/database.yml
    depends_on:
      - postgres
      - redis

  sidekiq:
    container_name: diaspora_sidekiq
    image: angristan/diaspora:0.7.5.0
    restart: always
    command: bin/bundle exec sidekiq
    volumes:
      - ./data:/diaspora/public/
      - ./diaspora.yml:/diaspora/config/diaspora.yml
      - ./database.yml:/diaspora/config/database.yml
    depends_on:
      - postgres
      - redis

  nginx:
    container_name: diaspora_nginx
    image: nginx:1.13
    restart: always
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/var/www/html
    ports:
      - 127.0.0.1:80:80
```

in my directory, there are the following files:
```
mrink@mrink MINGW64 /d/srv/diaspora
$ ls -ltr
total 45
-rw-r--r-- 1 mrink 1049089  1083 Jun 11 11:42 database.yml
-rw-r--r-- 1 mrink 1049089 29188 Jun 11 12:01 diaspora.yml
-rw-r--r-- 1 mrink 1049089   573 Jun 11 13:54 nginx-vhost.conf
drwxr-xr-x 1 mrink 1049089     0 Jun 11 13:56 data/
-rw-r--r-- 1 mrink 1049089  1435 Jun 12 09:47 docker-compose.yml
```
